" TODO: https://github.com/jreybert/vimagit
" TODO: Add to Brewfilw brew install fzf and brew install ripgrep
" TODO: Tab completion

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle. This must be first.
Plugin 'VundleVim/Vundle.vim'
Plugin 'joshdick/onedark.vim'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-surround'
Plugin 'vim-syntastic/syntastic'
Plugin 'tpope/vim-commentary'
Plugin 'vim-airline/vim-airline'
Plugin 'ycm-core/YouCompleteMe'

" Move up and down in autocomplete with <c-j> and <c-k>
inoremap <expr> <c-j> ("\<C-n>")
inoremap <expr> <c-k> ("\<C-p>")

" Git
"
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

"
" Fuzzy Search
"
set rtp+=~/.fzf
Plugin 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plugin 'junegunn/fzf.vim'
let $FZF_DEFAULT_COMMAND = 'find .'
nnoremap <C-p> :Files<cr>

"
" Language plugins
"
Plugin 'sheerun/vim-polyglot'
Plugin 'Chiel92/vim-autoformat'
au BufWrite * :Autoformat

"
" Rails
"
Plugin 'tpope/vim-rails'
Plugin 'thoughtbot/vim-rspec'
let g:rspec_runner = "os_x_iterm2"
let g:rspec_command = "Dispatch bundle exec rspec {spec}"
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

" -------------------------------------
" End of plugins

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" ==============================================================================
" Non-plugin stuff after this line
" ==============================================================================

"
" Colors
"
if (has("termguicolors"))
  set termguicolors
endif

" onedark.vim override: Don't set a background color when running in a terminal;
" just use the terminal's background color
" `gui` is the hex color code used in GUI mode/nvim true-color mode
" `cterm` is the color code used in 256-color mode
" `cterm16` is the color code used in 16-color mode
if (has("autocmd") && !has("gui_running"))
  augroup colorset
    autocmd!
    let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" }
    autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white }) " `bg` will not be styled since there is no `bg` setting
  augroup END
endif

colorscheme onedark

" use the space key as our leader. put this near the top of your vimrc
let mapleader = "\<space>"

" plugins
runtime! macros/matchit.vim " % matches on html tags, if/else, do/end, etc.

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
  let col = col('.') - 1
  if !col || getline('.')[col - 1] !~ '\k'
    return "\<Tab>"
  else
    return "\<C-p>"
  endif
endfunction
inoremap <Tab> <C-r>=InsertTabWrapper()<CR>
inoremap <S-Tab> <C-n>

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Switch between the last two files
nnoremap <Leader><Leader> <C-^>

" Triger `autoread` when files changes on disk
" https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
" https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif
" Notification after file change
" https://vi.stackexchange.com/questions/13091/autocmd-event-for-autoread
autocmd FileChangedShellPost *
      \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None

" When editing a file, always jump to the last known cursor position.
" Don't do it for commit messages, when the position is invalid, or when
" inside an event handler (happens when dropping a file on gvim).
autocmd BufReadPost *
      \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal g`\"" |
      \ endif

"
" File read/write
"
set autoread      " automatically read the current file when changed outside of vim
set autowrite     " automatically :write before running commands
set nobackup      " do not create a backup file on save
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287

" Strip trailing white spaces on save
function! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun

autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" tabs
set autoindent    " copy indent from current line when starting a new line
set expandtab
set shiftround
set shiftwidth=2
set smarttab
set tabstop=2

" display
set display+=lastline " display as much of the last line as possible
set laststatus=2      " always display the status line
set linebreak
set list listchars=tab:»·,trail:·,nbsp:·
set relativenumber
set numberwidth=5
set ruler             " show the cursor position all the time
set showcmd           " display incomplete commands
set title             " set the terminal title to the name of file being edited
syntax on

" scrolling
set scrolloff=1       " show at least 1 line above and below cursor
set sidescrolloff=5   " show at least 5 characters on either side of cursor

" autocomplete
set complete-=i           " autocomplete based on current and included files
set wildmenu              " use tab autocomplete in menus
set wildmode=list:longest " complete only up to the point of ambiguity while still showing you what your options are

"
" Search
"
set hlsearch   " highlight matching words
set ignorecase " search case insensitive
set incsearch  " do incremental searching (fuzzy search)
set smartcase  " search case sensitive only if there is a capital letter in the search expression

"This unsets the "last search pattern" register by hitting return
nnoremap <CR> :noh<CR><CR>

" misc
set backspace=2   " backspace deletes like most programs in insert mode
set history=1000
" set spell spelllang=en_us
set complete+=kspell
set clipboard=unnamed
if !empty(&viminfo)
  set viminfo^=!
endif

" Ref: https://vim.fandom.com/wiki/To_switch_back_to_normal_mode_automatically_after_inaction
" set 'updatetime' to 15 seconds when in insert mode
au InsertEnter * let updaterestore=&updatetime | set updatetime=15000
au InsertLeave * let &updatetime=updaterestore

" keybindings

" map ctrl-a to write the file
nmap <c-a> :w<cr>
imap <c-a> <esc>:w<cr>

" bind `q` to close the buffer for help files
autocmd filetype help nnoremap <buffer> q :q<cr>

autocmd Filetype gitcommit setlocal spell textwidth=72

if has('autocmd')
  filetype plugin indent on
endif

" move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk

" Navigate quick fix window
map <C-j> :cn<CR>
map <C-k> :cp<CR>

" split edit your vimrc. type space, v, r in sequence to trigger
nmap <leader>vr :sp $MYVIMRC<cr>

" source (reload) your vimrc. type space, s, o in sequence to trigger
nmap <leader>so :source $MYVIMRC<cr>
