#!/usr/bin/env bash

################################################################################
# Script Name: start
# Description: This script Creates a branch off main, assignes the Jira ticket to you, and transitions it to "In Progress"
# Author: Greg Answer
# License: MIT
#
# Dependencies:
#   - jq: https://jqlang.github.io/jq/tutorial
#
# Environment Variables (set in your ~/.bash_profile or where you prefer):
#   - JIRA_BASE_URL: Example if you work at Acme Inc, the url may be https://acme.atlassian.net
#   - JIRA_EMAIL: The email address associated with your Jira account
#   - JIRA_TOKEN: https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account
#   - GLAB_USERNAME: GitLab username can be found at https://gitlab.com/-/profile/account
#
# Usage: ./start C2-123 [options]
################################################################################


# When the `--debug` flag is passed to this script, display the file and line number for each command that executed.
[[ "${*}" =~ --debug ]] && set -o xtrace
PS4='+ ${BASH_SOURCE}:${LINENO} '
set -o pipefail # `error here | true` will fail if this is enabled.
set -o errexit # Exit the script when an error occurs.


user_input_jira_id="$1"

confirm() {
  echo
  read -p "${1} (y/n) " -n 1 input
  echo
  [[ "${input}" =~ ^[Yy]$ ]] && return 0 || return 1
}


# Fail without user input.

if [ -z "$user_input_jira_id" ]; then
  echo -e "Jira ID required."
  exit 1
fi


# Fetch the Jira issue.

echo "Fetching $user_input_jira_id Jira issue..."
issue_url="$JIRA_BASE_URL/rest/api/latest/issue/$user_input_jira_id"
response=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" -H "Content-Type: application/json" "$issue_url")
issue_id=$(echo "$response" | jq -r '.key')
issue_title=$(echo "$response" | jq -r '.fields.summary')


# Confirm the issue is correct.

if [ "$issue_id" == "null" ]; then
  echo -e "$response"
  exit 1
fi
confirm "$issue_id: $issue_title?" || exit


# Create the branch.

issue_type=$(echo "$response" | jq -r '.fields.issuetype.name')
branch=$(echo "$issue_id-$issue_type-$GLAB_USERNAME" | sed 's/ /-/g')
echo "Creating '$branch' branch off of main..."
git checkout main && git pull && git checkout -b "$branch"


# Set Jira ticket "In Progress".

echo "Setting Jira ticket 'In Progress'..."
transition_url="$JIRA_BASE_URL/rest/api/latest/issue/$issue_id/transitions"
response=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" "Content-Type: application/json" "$transition_url")
transition_id=$(echo "$response" | jq -r '.transitions[] | select(.name == "In Progress") | .id')
transition_data='{"transition": {"id": "'"$transition_id"'"}}'
response=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" -X POST -H "Content-Type: application/json" --data "$transition_data" "$transition_url")
echo -e "$response"


# Assign me to the ticket.

echo "Assigning ticket to self"
response=$(curl \
  --silent \
  --user "$JIRA_EMAIL:$JIRA_TOKEN" \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --request PUT \
  --url "$JIRA_BASE_URL/rest/api/latest/issue/$issue_id/assignee" \
  --data '{ "accountId": "'"$JIRA_ACCOUNT_ID"'" }'
)
echo -e "$response"
