tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'

brew 'awscli'
brew 'aws-iam-authenticator'
brew 'bash-completion'
brew 'coreutils'
brew 'cmake'
brew 'docker-compose'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'glab'
brew 'go'
brew 'hub'
brew 'java'
brew 'jq'
brew 'libssh2'
brew 'libusb-compat'
brew 'libyubikey'
brew 'mas'
brew 'nodejs'
brew 'notion'
brew 'openssl'
brew 'postgresql@14'
brew 'python'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ripgrep'
brew 'ruby-build'
brew 'shellcheck'
brew 'tmux'
brew 'the_silver_searcher'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-syntax-highlighting'

cask 'google-chrome'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'kindle'
cask 'postman'
cask 'postman'
cask 'slack'
cask 'spotify'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'vlc'

# Zoom is just Zoom now.
cask 'zoom'

# Mac App Store is dependent on Apple ID sign in. Temporarily commented out.
# mas "Magnet", id: 441258766

### Archived

# auto is not working for some reason.
# brew 'auto'

# brew "macmediakeyforwarder" # Not working at the moment.
# cask 'caskroom/fonts/font-inconsolata'
# cask 'chromedriver'
# cask 'docker'
# cask 'firefox'
# cask 'flux'
# cask 'robo-3t'
# cask 'sensiblesidebuttons'
# cask 'whatsapp'
